const { chromium, expect } = require('@playwright/test')
const fs = require('node:fs/promises')
;(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true })
  try {
    const context = await browser.newContext({ baseURL: 'http://127.0.0.1:18000' })
    const errors = []
    const page = await context.newPage()
    page.on('pageerror', error => errors.push(error.message))
    const login = await context.request.post('/api/method/login', {
      form: { usr: 'dev2.agent.a@example.invalid', pwd: 'Local-Dev2-Only-2026' },
    })
    expect(login.status()).toBe(200)
    await page.goto('/crm-agent')
    await expect(page.locator('body')).not.toContainText('{{')
    expect(await page.locator('meta[name=site-timezone]').getAttribute('content')).not.toContain('{{')
    await expect(page.getByRole('heading', { name: 'My leads', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'New lead', exact: true }).click()
    const name = 'Browser prospect ' + Date.now()
    await page.getByLabel('First name', { exact: true }).fill(name)
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Add contact', exact: true }).click()
    await page.getByLabel('First name', { exact: true }).fill('Browser contact')
    await page.getByLabel('Email', { exact: true }).fill('browser.contact@example.invalid')
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(page.locator('#detail')).toContainText('browser.contact@example.invalid')
    await page.getByRole('button', { name: 'Add follow-up', exact: true }).click()
    await page.getByLabel('What needs doing?').fill('Call browser prospect')
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(page.locator('#detail')).toContainText('Call browser prospect')
    await page.getByRole('button', { name: 'Mark done', exact: true }).click()
    await expect(page.locator('#detail')).toContainText(/Call browser prospect.*Done/)
    await page.getByRole('button', { name: 'Book appointment', exact: true }).click()
    const appointmentTitle = 'Meeting ' + Date.now()
    await page.getByLabel('Appointment title', { exact: true }).fill(appointmentTitle)
    await page.getByLabel(/^Starts \(/).fill('2035-06-12T10:00')
    await page.getByLabel(/^Ends \(/).fill('2035-06-12T11:00')
    await page.getByLabel('Location or meeting URL').fill('Client office')
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    const appointment = page.locator('article').filter({ hasText: appointmentTitle })
    await expect(appointment).toContainText('Client office')
    await appointment.getByRole('button', { name: 'Reschedule / edit', exact: true }).click()
    await page.getByLabel(/^Starts \(/).fill('2035-06-12T12:00')
    await page.getByLabel(/^Ends \(/).fill('2035-06-12T13:00')
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(appointment).toContainText('12:00:00')
    await appointment.getByRole('button', { name: 'Complete appointment', exact: true }).click()
    await expect(appointment).toContainText('Completed')
    await page.getByRole('button', { name: 'Next', exact: true }).click()
    await expect(appointment).toHaveCount(0)
    await page.getByRole('button', { name: 'Previous', exact: true }).click()
    await expect(appointment).toContainText('Completed')
    await fs.mkdir('test-results' , { recursive: true })
    await page.screenshot({ path: 'test-results/agent-workspace.png', fullPage: true })
    expect(errors).toEqual([])
    await page.getByRole('button', { name: 'Sign out', exact: true }).click()
    await expect(page).toHaveURL(/\/login/)
    console.log('PASS: browser lead/contact/follow-up and appointment create/reschedule/complete/navigation workflow and logout; no JS errors.')
  } finally { await browser.close() }
})().catch(error => { console.error(error); process.exitCode = 1 })
