const { chromium, expect } = require('@playwright/test')
const fs = require('node:fs/promises')
;(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true })
  try {
    const context = await browser.newContext({ baseURL: 'http://127.0.0.1:18000', viewport: { width: 1440, height: 960 } })
    await context.addInitScript(() => localStorage.setItem('crm_persona_captured', '1'))
    const page = await context.newPage()
    const errors = []
    page.on('pageerror', error => errors.push(error.message))
    expect((await context.request.post('/api/method/login', { form: { usr: 'Administrator', pwd: 'Local-Dev2-Only-2026' } })).status()).toBe(200)
    await page.goto('/crm/erpnext-sync')
    await expect(page.getByRole('heading', { name: 'ERPNext sync', exact: true })).toBeVisible()
    const onboarding = page.locator('div.fixed.z-50.right-0.w-80')
    if (await onboarding.isVisible()) await onboarding.locator(':scope > div').first().getByRole('button').last().click()
    if (await page.getByRole('button', { name: 'Disable sync', exact: true }).isVisible()) await page.getByRole('button', { name: 'Disable sync', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Enable Lead sync', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Enable Lead sync', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Sync now', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Sync now', exact: true }).click()
    await expect(page.locator('p[role=status]')).toContainText('Pass complete.', { timeout: 30000 })
    await expect(page.locator('details')).not.toHaveCount(0)
    await page.getByRole('button', { name: 'Sync now', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Sync now', exact: true })).toBeEnabled({ timeout: 30000 })
    await page.getByRole('button', { name: 'Turn on automatic sync', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Turn off automatic sync', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Disable sync', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Enable Lead sync', exact: true })).toBeVisible()
    await page.locator('details').first().locator('summary').click()
    await fs.mkdir('test-results', { recursive: true })
    await page.screenshot({ path: 'test-results/erpnext-sync.png', fullPage: true })
    await page.setViewportSize({ width: 390, height: 844 })
    await page.reload()
    await expect(page.getByRole('heading', { name: 'ERPNext sync', exact: true })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    expect(errors).toEqual([])
    for (const user of ['dev2.sales.a@example.invalid', 'dev2.agent.a@example.invalid']) {
      const denied = await browser.newContext({ baseURL: 'http://127.0.0.1:18000' })
      expect((await denied.request.post('/api/method/login', { form: { usr: user, pwd: 'Local-Dev2-Only-2026' } })).status()).toBe(200)
      expect((await denied.request.get('/api/method/crm.migration.sync.status')).status()).toBe(403)
      await denied.close()
    }
    console.log('PASS: admin sync controls, repeat run, history, mobile width, salesperson/agent denied; sync disabled after test')
  } finally { await browser.close() }
})().catch(error => { console.error(error); process.exitCode = 1 })
